name: mini_logger
description: A package about the log, supports color printing, local storage, query, delete, upload events.
version: 3.41.9
homepage: https://github.com/collectFlutter/mini_logger

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.0
  ansicolor: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

